# Generated by Django 5.2.6 on 2025-09-22 13:47

import django.db.models.deletion
import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0002_integrante_mascota_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_cuota', models.CharField(choices=[('CUOTA', 'Cuota'), ('MULTA', 'Multa')], max_length=10)),
                ('fecha_a_pagar', models.DateField()),
                ('periodo', models.CharField(default=finanzas.models.periodo_actual_str, max_length=7)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('VENCIDA', 'Vencida'), ('PAGADA', 'Pagada'), ('PARCIAL', 'Parcial'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='unidades.unidadhabitacional')),
            ],
            options={
                'verbose_name': 'Cuota/Multa',
                'verbose_name_plural': 'Cuotas/Multas',
                'db_table': 'cuota',
                'indexes': [models.Index(fields=['unidad', 'periodo'], name='cuota_unidad__67f5ae_idx'), models.Index(fields=['estado'], name='cuota_estado_4a4514_idx'), models.Index(fields=['tipo_cuota'], name='cuota_tipo_cu_d066d4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_pago__gte', 0)), name='chk_cuota_cantidad_pos')],
            },
        ),
    ]
