# Generated by Django 5.2.6 on 2025-09-23 02:30

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0002_areacomun_precio_base'),
        ('finanzas', '0002_enable_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('areacomun', models.ForeignKey(db_column='areacomun_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='amenities.areacomun')),
                ('usuario', models.ForeignKey(db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['-fecha_inicio', '-id'],
                'indexes': [models.Index(fields=['areacomun'], name='ix_reserva_area'), models.Index(fields=['usuario'], name='ix_reserva_usuario')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='chk_reserva_rango'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'APROBADA'])), expressions=[(models.F('areacomun'), '='), (models.Func(models.F('fecha_inicio'), models.F('fecha_fin'), function='tstzrange'), '&&')], name='excl_reserva_solape_por_area')],
            },
        ),
    ]
