# Generated by Django 5.2.6 on 2025-09-23 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_reserva'),
        ('unidades', '0002_integrante_mascota_visita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('nit', models.CharField(max_length=30)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'Pago QR'), ('BANCO', 'Depósito/Banking'), ('TARJETA', 'Tarjeta')], max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='finanzas.cuota')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='finanzas.reserva')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidadhabitacional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'indexes': [models.Index(fields=['estado'], name='factura_estado_5c3001_idx'), models.Index(fields=['fecha'], name='factura_fecha_ffac0b_idx'), models.Index(fields=['numero', 'serie'], name='factura_numero_56ee43_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_factura_total_no_negativo'), models.CheckConstraint(condition=models.Q(models.Q(('reserva__isnull', True), ('cuota__isnull', False)), models.Q(('reserva__isnull', False), ('cuota__isnull', True)), _connector='OR'), name='chk_factura_xor_reserva_o_cuota')],
            },
        ),
    ]
