# Generated by Django 5.2.6 on 2025-09-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='deposito',
        ),
    ]
