# Generated by Django 5.2.6 on 2025-09-24 02:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_remove_reserva_deposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('QR', 'Pago QR'), ('BANCO', 'Depósito/Banking'), ('TARJETA', 'Tarjeta')], max_length=30),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('QR', 'Pago QR'), ('BANCO', 'Depósito/Banking'), ('TARJETA', 'Tarjeta')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_url', models.TextField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='finanzas.factura')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'indexes': [models.Index(fields=['estado'], name='pago_estado_e7b4e1_idx'), models.Index(fields=['fecha_pago'], name='pago_fecha_p_e0ee42_idx'), models.Index(fields=['factura'], name='pago_factura_9cd68b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='chk_pago_monto_no_negativo')],
            },
        ),
    ]
