# Generated by Django 5.2.6 on 2025-09-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['creado_en'], name='auditoria_b_creado__2a0c13_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario'], name='auditoria_b_usuario_3713fd_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['path'], name='auditoria_b_path_0f9de5_idx'),
        ),
    ]
