# Generated by Django 5.2.6 on 2025-09-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('areacomun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='amenities.areacomun')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='vision.zona')),
            ],
        ),
        migrations.CreateModel(
            name='DeteccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.FloatField()),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('otro', 'Otro')], max_length=20)),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='bajo', max_length=20)),
                ('incidencia', models.CharField(choices=[('robo', 'Robo'), ('vandalismo', 'Vandalismo'), ('incendio', 'Incendio'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='vision.camara')),
            ],
        ),
    ]
