# Generated by Django 5.2.6 on 2025-09-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0002_areacomun_precio_base'),
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='areacomun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camaras', to='amenities.areacomun'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento')], db_index=True, default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='camara',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camaras', to='vision.zona'),
        ),
        migrations.AlterField(
            model_name='deteccionia',
            name='camara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detecciones', to='vision.camara'),
        ),
        migrations.AlterField(
            model_name='deteccionia',
            name='evidencia',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('otro', 'Otro')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deteccionia',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deteccionia',
            name='incidencia',
            field=models.CharField(choices=[('robo', 'Robo'), ('vandalismo', 'Vandalismo'), ('incendio', 'Incendio'), ('otro', 'Otro')], db_index=True, default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='deteccionia',
            name='nivel_riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], db_index=True, default='bajo', max_length=20),
        ),
        migrations.AlterField(
            model_name='zona',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento')], db_index=True, default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
