# Generated by Django 5.2.6 on 2025-09-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('permanente', 'Permanente'), ('temporal', 'Temporal'), ('visita', 'Visita')], default='temporal', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('revocado', 'Revocado'), ('usado', 'Usado'), ('vencido', 'Vencido')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valido_hasta', models.DateTimeField(blank=True, null=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='vehiculos.vehiculo')),
            ],
        ),
    ]
