# Generated by Django 5.2.6 on 2025-09-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
