# Generated by Django 5.2.6 on 2025-09-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('bloque', models.CharField(max_length=30)),
                ('estado', models.CharField(default='ACTIVA', max_length=20)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'ordering': ['bloque', 'numero'],
                'indexes': [models.Index(fields=['bloque', 'numero'], name='unidades_un_bloque_ba0179_idx')],
                'constraints': [models.UniqueConstraint(fields=('bloque', 'numero'), name='uniq_unidad_bloque_numero')],
            },
        ),
        migrations.CreateModel(
            name='ResidenteUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_propietario', models.BooleanField(default=False)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='authx.residente')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='unidades.unidadhabitacional')),
            ],
            options={
                'indexes': [models.Index(fields=['unidad'], name='unidades_re_unidad__832a6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('residente', 'unidad'), name='uniq_residente_unidad')],
            },
        ),
    ]
