# Generated by Django 5.2.6 on 2025-09-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=200)),
                ('registro_facial', models.CharField(max_length=200)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='unidades.unidadhabitacional')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=200)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='unidades.unidadhabitacional')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_hora_llegada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='unidades.unidadhabitacional')),
            ],
        ),
    ]
