# Generated by Django 5.2.6 on 2025-09-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_mantenimiento', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('prioridad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='authx.personal')),
            ],
        ),
    ]
